[[can]]
channel = "can0"
bustype = "socketcan"
bitrate = 500000
listenonly = false

[thinedge]
mqtthost = "127.0.0.1"
mqttport = 1883

[service]
loglevel = "DEBUG"
transmitrate = 5
combinemeasurements = true