[[device]]
name = "test_device"
channel = "can0"

[[device.registers]]
number = "0x18FEEE81"
offset = -30
factor = 1
startBit = 16
noBits = 8
on_change = false       #default false
datatype = "integer"    #default integer / optionally float
signed = false          #default unsigned(false) / optionally signed(true) ;only integer
measurementmapping.templatestring="{\"OQS_Sensor\":{\"Temperature\":%% }}" 

[[device.registers]]
number = "0x18FEFF81"
offset = 0
factor = 10
startBit = 40
noBits = 8
measurementmapping.templatestring="{\"OQS_Sensor\":{\"Oilquality\":%% }}" 