[[device]]
name = "connectedge_test_device"
channel = "can0"

[[device.registers]]
number = "0xA1"
input = false
divisor = 1
unit = ""
decimalPlaces = 0
offset = 0
multiplier = 1
startBit = 0
noBits = 64
name = "Test"
signed = false
id = "7292838253431274"
measurementmapping.templatestring="{\"Waterpump\":{\"Temperature\":%% }}" 
eventmapping.text="This event should be created on value change"
eventmapping.type="TestEvent"

[[device.registers]]
number = "0xA2"
input = false
divisor = 1
unit = ""
decimalPlaces = 0
offset = 0
multiplier = 1
startBit = 0
noBits = 16
name = "Test"
signed = true
id = "7292838253431274"
measurementmapping.templatestring="{\"Waterpump\":{\"Power\":%% }}" 